// 1ページの表示件数
export const LIMIT = 12;

export const CONTACT_URL = "https://forms.gle/7zHKhHzHJVD8a5tJ8";

export const cities = [
    {id: "1", name: "那覇市"},
    {id: "2", name: "沖縄市"},
    {id: "3", name: "うるま市"},
    {id: "4", name: "浦添市"},
    {id: "5", name: "宜野湾市"},
    {id: "6", name: "名護市"},
    {id: "7", name: "豊見城市"},
    {id: "8", name: "糸満市"},
    {id: "9", name: "宮古島市"},
    {id: "10", name: "石垣市"},
    {id: "11", name: "南城市"},
    {id: "12", name: "読谷村"},
    {id: "13", name: "南風原町"},
    {id: "14", name: "西原町"},
    {id: "15", name: "八重瀬町"},
    {id: "16", name: "北谷町"},
    {id: "17", name: "中城村"},
    {id: "18", name: "与那原町"},
    {id: "19", name: "北中城村"},
    {id: "20", name: "嘉手納町"},
    {id: "31", name: "本部町"},
    {id: "32", name: "金武町"},
    {id: "33", name: "恩納村"},
    {id: "34", name: "今帰仁村"},
    {id: "35", name: "久米島町"},
    {id: "36", name: "宜野座村"},
    {id: "37", name: "国頭村"},
    {id: "38", name: "伊江村"},
    {id: "39", name: "竹富町"},
    {id: "40", name: "大宜味村"},
    {id: "41", name: "与那国町"},
    {id: "42", name: "東村"},
    {id: "43", name: "伊是名村"},
    {id: "44", name: "南大東村"},
    {id: "45", name: "伊平屋村"},
    {id: "46", name: "多良間村"},
    {id: "47", name: "座間味村"},
    {id: "48", name: "粟国村"},
    {id: "49", name: "渡嘉敷村"},
    {id: "50", name: "北大東村"},
    {id: "51", name: "渡名喜村"},
] as const

export const cityNameList = cities.map((city) => city.name)
